// SETTINGS CONSTANTS
export const LOGO_BG = "LOGO_BG";
export const NAVBAR_BG = "NAVBAR_BG";
export const SIDEBAR_BG = "SIDEBAR_BG";
export const THEME = "THEME";
export const DIRECTION = "DIRECTION";
export const SIDEBAR_POSITION = "SIDEBAR_POSITION";
export const HEADER_POSITION = "HEADER_POSITION";
export const LAYOUT = "LAYOUT";
export const SIDEBAR_TYPE = "SIDEBAR_TYPE";
export const CONFIRM_BUTTON_COLOR = "CONFIRM_BUTTON_COLOR";
export const CANCEL_BUTTON_COLOR = "CANCEL_BUTTON_COLOR";

// CHAT CONSTANTS
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const SELECTED_CHAT = "SELECTED_CHAT";
export const SEARCH_USER = "SEARCH_USER";
export const MSG_SUBMIT = "MSG_SUBMIT";

// TODO CONSTANTS
export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE";
export const TOGGLE_STARRED_TODO = "TOGGLE_STARRED_TODO";
export const SET_VISIBILITY_FILTER_TODO = "SET_VISIBILITY_FILTER_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TODO_DETAILS = "TODO_DETAILS";
export const FILTER_TODO = "FILTER_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const ADD_TODO = "ADD_TODO";

// CONTACT CONSTANTS
export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const CONTACT_DETAILS = "CONTACT_DETAILS";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const FILTER_CONTACT = "FILTER_CONTACT";
export const TOGGLE_STARRED_CONTACT = "TOGGLE_STARRED_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";

// EMAIL CONSTANTS
export const STAR_EMAIL = "STAR_EMAIL";
export const IMPORTANT_EMAIL = "IMPORTANT_EMAIL";
export const OPEN_EMAIL = "OPEN_EMAIL";
export const TRASH_EMAIL = "TRASH_EMAIL";
export const ASSIGN_FOLDER = "ASSIGN_FOLDER";
export const ASSIGN_LABEL = "ASSIGN_LABEL";
export const SET_SELECTED_EMAIL = "SET_SELECTED_EMAIL";
export const FILTER_EMAIL = "FILTER_EMAIL";
export const SET_EMAIL_VISIBILITY_FILTER = "SET_EMAIL_VISIBILITY_FILTER";

// NOTES CONSTANTS
export const SELECTED_NOTES = "SELECTED_NOTES";
export const SEARCH_NOTES = "SEARCH_NOTES";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const ADD_NOTE = "ADD_NOTE";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";

// LOGIN USER CONSTANTS
export const LOGIN_USER_ID          = "LOGIN_USER_ID";
export const LOGIN_USER_NAME        = "LOGIN_USER_NAME";
export const LOGIN_USER_EMAIL       = "LOGIN_USER_EMAIL";
export const LOGIN_USER_PHOTO       = "LOGIN_USER_PHOTO";
export const LOGIN_USER_STATE       = "LOGIN_USER_STATE";
export const LOGIN_USER_LAST_LOGIN  = "LOGIN_USER_LAST_LOGIN";
export const LOGIN_USER_PERMISSIONS = "LOGIN_USER_PERMISSIONS";
export const LOGIN_USER_SUPER_USER  = "LOGIN_USER_SUPER_USER";

// TOASTIFY
export const TOASTIFY_POSITION                   = "TOASTIFY_POSITION";
export const TOASTIFY_ENABLE_NEWEST_ON_TOP       = "TOASTIFY_ENABLE_NEWEST_ON_TOP";
export const TOASTIFY_DISABLE_NEWEST_ON_TOP      = "TOASTIFY_DISABLE_NEWEST_ON_TOP";
export const TOASTIFY_ENABLE_RTL                 = "TOASTIFY_ENABLE_RTL";
export const TOASTIFY_DISABLE_RTL                = "TOASTIFY_DISABLE_RTL";
export const TOASTIFY_AUTOCLOSE                  = "TOASTIFY_AUTOCLOSE";
export const TOASTIFY_ENABLE_CLOSE_ONCLICK       = "TOASTIFY_ENABLE_CLOSE_ONCLICK";
export const TOASTIFY_DISABLE_CLOSE_ONCLICK      = "TOASTIFY_DISABLE_CLOSE_ONCLICK";
export const TOASTIFY_ENABLE_DRAGGABLE           = "TOASTIFY_ENABLE_DRAGGABLE";
export const TOASTIFY_DISABLE_DRAGGABLE          = "TOASTIFY_DISABLE_DRAGGABLE";
export const TOASTIFY_ENABLE_PAUSE_ONHOVER       = "TOASTIFY_ENABLE_PAUSE_ONHOVER";
export const TOASTIFY_DISABLE_PAUSE_ONHOVER      = "TOASTIFY_DISABLE_PAUSE_ONHOVER";
export const TOASTIFY_ENABLE_PAUSE_ON_FOCUSLOSS  = "TOASTIFY_ENABLE_PAUSE_ON_FOCUSLOSS";
export const TOASTIFY_DISABLE_PAUSE_ON_FOCUSLOSS = "TOASTIFY_DISABLE_PAUSE_ON_FOCUSLOSS";
export const TOASTIFY_HIDE_PROGRESSBAR           = "TOASTIFY_HIDE_PROGRESSBAR";
export const TOASTIFY_SHOW_PROGRESSBAR           = "TOASTIFY_SHOW_PROGRESSBAR";

// Message Modal
export const MESSAGE_MODAL_SET_ID = "MESSAGE_MODAL_SET_ID";
export const MESSAGE_MODAL_OPEN = "MESSAGE_MODAL_OPEN";
export const MESSAGE_MODAL_CLOSE = "MESSAGE_MODAL_CLOSE";

// Routes
export const ROUTES = "ROUTES";

// Times
export const SERVER_TIME_OFFSET = "SERVER_TIME_OFFSET";

// Modal
export const MODAL_PASSWORD_CHANGE_SET_ID    = "MODAL_PASSWORD_CHANGE_SET_ID";
export const MODAL_PASSWORD_CHANGE_OPEN      = "MODAL_PASSWORD_CHANGE_OPEN";
export const MODAL_PASSWORD_CHANGE_CLOSE     = "MODAL_PASSWORD_CHANGE_CLOSE";

// Modal Search Account
export const MODAL_SEARCH_ACCOUNT_OPEN       = "MODAL_SEARCH_ACCOUNT_OPEN";
export const MODAL_SEARCH_ACCOUNT_CLOSE      = "MODAL_SEARCH_ACCOUNT_CLOSE";

// Modal Notification
export const MODAL_NOTIFICATION_SET_ID = "MODAL_NOTIFICATION_SET_ID";
export const MODAL_NOTIFICATION_OPEN   = "MODAL_NOTIFICATION_OPEN";
export const MODAL_NOTIFICATION_CLOSE  = "MODAL_NOTIFICATION_CLOSE";

// Modal Notification
export const MODAL_LOADING_OPEN   = "MODAL_LOADING_OPEN";
export const MODAL_LOADING_CLOSE  = "MODAL_LOADING_CLOSE";

// Permissions
export const PERMISSIONS = "PERMISSIONS";

// TAX
export const TAX_BASIC_RATE = "TAX_BASIC_RATE";
export const TAX_LIST       = "TAX_LIST";

// Kubun
export const KUBUN_MITSUMORI_STATUSES    = "KUBUN_MITSUMORI_STATUSES";
export const KUBUN_KEISHOU               = "KUBUN_KEISHOU";
export const KUBUN_TANI                  = "KUBUN_TANI";
export const KUBUN_TANI_CACHED           = "KUBUN_TANI_CACHED";
export const KUBUN_JUUYOUDO              = "KUBUN_JUUYOUDO";
export const KUBUN_JUUYOUDO_CACHED       = "KUBUN_JUUYOUDO_CACHED";
export const KUBUN_SHOUDAN_STATUS        = "KUBUN_SHOUDAN_STATUS";
export const KUBUN_SHOUDAN_STATUS_CACHED = "KUBUN_SHOUDAN_STATUS_CACHED";

// hanbai
export const HANBAI_TORIHIKISAKI_TAGS = "HANBAI_TORIHIKISAKI_TAGS";
export const HANBAI_JUCHUU_STATUSES   = "HANBAI_JUCHUU_STATUSES";

// Notifications
export const NOTIFICATIONS_COUNT    = "NOTIFICATIONS_COUNT";
export const NOTIFICATIONS_INTERVAL = "NOTIFICATIONS_INTERVAL";
