# Generated by Django 3.2.2 on 2022-02-26 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetteiModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('setteimei', models.CharField(max_length=64, unique=True, verbose_name='Setting Name')),
                ('setteichi', models.TextField(blank=True, default='', verbose_name='Setting Value')),
                ('created_by', models.ForeignKey(db_column='created_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='settei_setteimodel_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('modified_by', models.ForeignKey(db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='settei_setteimodel_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
            ],
            options={
                'verbose_name': 'Setting',
                'db_table': 's_settei',
            },
        ),
    ]
