# Generated by Django 4.2.4 on 2023-08-06 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import soft_delete.models.datetimeflag_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Ex. Web', max_length=20, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('created_by', models.ForeignKey(db_column='created_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('modified_by', models.ForeignKey(db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('deleted_at', soft_delete.models.datetimeflag_field.DateTimeFlagField(blank=True, null=True, verbose_name='Deleted')),
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Ex. Python powered examples.', max_length=100, verbose_name='Blog Title')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='記事の抜粋')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='画像')),
                ('category', models.ManyToManyField(blank=True, related_name='categories', to='blog.categorymodel', verbose_name='カテゴリー')),
                ('created_by', models.ForeignKey(db_column='created_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('modified_by', models.ForeignKey(db_column='modified_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'db_table': 'blog_posts',
            },
        ),
    ]
