# Generated by Django 4.2.4 on 2023-08-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='slug',
        ),
    ]
