# Generated by Django 3.2.21 on 2023-11-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_categorymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開'),
        ),
    ]
