# Generated by Django 4.2.14 on 2024-08-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodel_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='下書き'),
        ),
    ]
