# Generated by Django 5.1.4 on 2025-02-15 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 20, 59, 23, 705159, tzinfo=datetime.timezone.utc), verbose_name='publish_date'),
        ),
    ]
