# Generated by Django 4.2.4 on 2025-12-14 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(default='', help_text='Ex. Web', max_length=20, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 5, 57, 43, 301462, tzinfo=datetime.timezone.utc), verbose_name='publish_date'),
        ),
    ]
